### ISSUE TITLE
InterpolationSyntaxError when referencing a variables multiple times

### ISSUE THREAD

**Issue by JonZeolla** [bro/package-manager#10]
This appears to be a bug.

In my bro-pkg.meta file, I have a rather long `build_command` (see #9 for why that is), but one section of that is as follows:
```
./configure --bro-dist=%(bro_dist)s --with-librdkafka=/usr/local --install-root=%(bro_dist)/lib/bro/plugins
```

When I attempt to do a `bro-pkg install`, I get the following error which seems to indicate an inability to interpolate the same variable twice.

```
InterpolationSyntaxError: bad interpolation variable reference u'%(bro_dist)/lib/bro/plugins && make)'
```

I have a reproducible example [here](https://github.com/JonZeolla/metron-bro-plugin-kafka/blob/a7637c56e62cf483f3a2c619c560e519f1158ba5/bro-pkg.meta).  Screenshot below.

![interpolationsyntaxerror](https://user-images.githubusercontent.com/1385510/30357231-35866032-9803-11e7-8021-e9d1a438ec6b.png)

**Comment by jsiwek** [comment]
It looks like the second substitution is just typo'd/malformed

e.g. the first one is `%(bro_dist)s`

and the second one is `%(bro_dist)`

Note the missing 's' character at the end.

**Comment by JonZeolla** [comment]
I don't recall seeing that in any documentation, can it get added or can you point me to where to look?  I did look multiple times.

**Comment by jsiwek** [comment]
> I don't recall seeing that in any documentation, can it get added or can you point me to where to look?

It's mentioned in this section: http://bro-package-manager.readthedocs.io/en/stable/package.html#build-command

Though, I can easily add a more dedicated section covering the substitution format.   It could maybe describe that the substitution format functionality comes from Python's configparser module and that any field from your ~/.bro-pkg/config file is eligible to be substituted into the package metadata, I'm realizing now it may not have been clear what was going on there.

Did you have a particular place in the docs you first tried to look or think makes sense to expand?

**Comment by JonZeolla** [comment]
Right, I did see and read that section but it isn't very explicit in mentioning how that works.  Until your most recent message I was only guessing that the `s` types it as a string.  Your description regarding configparser was exactly what I was getting at - I would suggest a mention of the underlying mechanism, a brief description, and a pointer out to the configparser docs[1].

I would think to add the most detail about use of vars maybe here[2] and have references/brief explanations to it in all of the walkthroughs.

1: class ConfigParser.ConfigParser under https://docs.python.org/2/library/configparser.html for example
2: http://bro-package-manager.readthedocs.io/en/stable/package.html#package-metadata

**Comment by jsiwek** [comment]
The additions are in the master version of the docs now: http://bro-package-manager.readthedocs.io/en/latest/package.html

There's an additional "Value Interpolation" section and cross-references to it in the various other places of that doc where relevant.  Let me know if you review and still had suggestions, or feel free to submit a PR
