### ISSUE TITLE
Inability to solicit user feedback during bro-pkg install

### ISSUE THREAD

**Issue by JonZeolla** [bro/package-manager#11]
This is a feature request.

I have a bro package that I'm working on which I would like to be able to solicit feedback from the user, as it depends on the installation of an external library (See #9 for some details).  I attempted to do this using `read` but had to remove it [here](https://github.com/JonZeolla/metron-bro-plugin-kafka/commit/f1cc8a7cc6cb3d545cc8d4435dea91ab1f1e8bf1) as it appeared to not prompt the user and timed out.  It would be nice to be able to solicit user feedback (i.e. allow them to choose whether or not to install the package using my methods), especially because [`uninstall`](http://bro-package-manager.readthedocs.io/en/stable/bro-pkg.html#remove) would not properly remove the external library if it was added by the `bro-pkg install`.

**Comment by jsiwek** [comment]
I think ultimately addressing #9 will also address the particular concern here.  E.g. if bro-pkg has a standardized way of handling external dependencies it would just then extend the current confirmation prompts, something like:
```
The following packages will be INSTALLED:
  bro/jsiwek/bro-test-package (1.0.5)

The following external/platform packages will be INSTALLED:
  foo
  bar
  baz

Proceed? [Y/n]
```

If there were other applications/ideas for giving packages a mechanism to show arbitrary feedback prompts let me know or re-open.

**Comment by JonZeolla** [comment]
I agree but I wanted to note that users don't have the ability to reopen issues that somebody else closed even if they created it.
