### ISSUE TITLE
bro-pkg install . doesn't account for the currently checked out branch

### ISSUE THREAD

**Issue by JonZeolla** [bro/package-manager#12]
This is a feature request.

It appears that if you run `bro-pkg install .`, it requires that you are pointing to a local git repo, and it uses the master branch by default, regardless of the currently checked out branch (see screenshot below).  I would suggest that, when `bro-pkg install` is run and points to a local directory, it could:
1. Use the currently checked-out branch.
1. Notify the user that the currently checked out branch isn't being used by `bro-pkg install`, and they should consider using `--version`.
1. Something else.

![local bro-pkg install](https://user-images.githubusercontent.com/1385510/30397252-dd431890-9891-11e7-9a02-9ceb773fbb3b.png)

**Comment by jsiwek** [comment]
In bro-pkg 'master', it's been changed to use the currently checked out branch, probably expect a new release version next week.
