### ISSUE TITLE
Bro version dependency

### ISSUE THREAD

**Issue by dopheide-esnet** [bro/package-manager#15]
There's really two issues here starting with this:

First:
error: failed to resolve dependencies: unsatisfiable dependency: "bro" (2.5-297) is installed, but "bro/ncsa/bro-simple-scan" requires >=2.5.1

from Justin:
"I think this may be an issue in bro-pkg.. I’m not sure what I should be doing in this case.  I said >= 2.5.1, and you are using a version that was released after 2.5.1, so I’d expect it to work.

I’m not sure why the bro version is 2.5-297 and not 2.5.1-297.. That may be part of the problem?"

I tend to agree that Bro's version should reflect that it's 2.5.1 rather than expect package developers to know what sub-version corresponds, but that could also be something automatically known to bro-pkg.

The second issue is that it would be nice if bro-pkg allowed the user to override the dependency and continue the installation (much like a failed test suite does).

**Comment by jsiwek** [comment]
> "I think this may be an issue in bro-pkg.. I’m not sure what I should be doing in this case. I said >= 2.5.1, and you are using a version that was released after 2.5.1, so I’d expect it to work.
> 
> I’m not sure why the bro version is 2.5-297 and not 2.5.1-297.. That may be part of the problem?"

Yeah, it's part of the problem.  I think the versioning process for Bro's patch-level releases breaks off a branch from master to do the release.  So you'd have the VCS version increments still being appended to the last minor release version (without the new patch-level).

I think this may be an "ok" way for Bro to do things, but the big problem with 2.5.1 is that it's not really just a "patch-level" release as the versioning semantics implies.  It had some new features and API changes (as noted in https://github.com/ncsa/bro-simple-scan/issues/1).  So it probably should have been versioned as 2.6.  i.e. I think it should be rare for packages to have to depend on a patch-level release, and for those cases, it's probably fine for the package author to specify the minor-level + VCS (e.g. ">=2.5-307") as that just allow both the master branch and patch-level release to satisfy it.

For now, I'm suggesting this changeset to the package: https://github.com/ncsa/bro-simple-scan/pull/3

> The second issue is that it would be nice if bro-pkg allowed the user to override the dependency and continue the installation (much like a failed test suite does).

Agreed, I'll keep this issue open until that's implemented.
