### ISSUE TITLE
Add recommended packages to metadata.

### ISSUE THREAD

**Issue by J-Gras** [bro/package-manager#22]
Some packages might not _depend_ on other packages but installing them might be recommended. For example, bro-doctor will recommend add-node-names: https://github.com/ncsa/bro-doctor/pull/6
I can think of two possibilities to realize that:
1. Add a new `recommended` field.
```
depends =
  bro >=2.5.0
  foo *
recommended =
  https://github.com/bro/bar >=2.0.0
  bas ==1.0.0
```
2. Mark dependencies as optional.
```
depends =
  bro >=2.5.0
  foo *
  +https://github.com/bro/bar >=2.0.0
  +bas ==1.0.0
```
Ideally bro-pkg would ask separately whether optional packages should be installed.

**Comment by jsiwek** [comment]
Yeah, that's a good idea.  I'll probably go with a new 'suggests' metadata field.

**Comment by jsiwek** [comment]
Just sketching out design ideas for this in case there's feedback.  I'm thinking the following changes will work to implement this:

- start recognizing a 'suggests' field in bro-pkg.meta with same format as 'depends'
- treat suggestions like a normal dependency by default (i.e. `install`, `update`, or `bundle` will automatically install it).
- add an `--ignore-suggestions` flag to `install` command (also to `update` and `bundle`)
- modify return value of the [bropkg.manager.validate_dependencies() API](http://bro-package-manager.readthedocs.io/en/latest/api/manager.html#bropkg.manager.Manager.validate_dependencies) to indicate the list of all suggested packages

Here's what a user would see:

```
$ bro-pkg install bro-test-package
The following packages will be INSTALLED:
  bro/jsiwek/bro-test-package (1.0.5)
  bro/jsiwek/another-package (1.0.0) (suggested)
  bro/jsiwek/some-package (1.0.1) (suggested)

Proceed? [Y/n]
```

If they abort because they don't want want suggestions, they can do:

```
$ bro-pkg install --ignore-suggestions bro-test-package
The following packages will be INSTALLED:
  bro/jsiwek/bro-test-package (1.0.5)

Proceed? [Y/n]
```

If they wanted to pick-and-choose from suggestions, they can always explicitly `install` each one.

It may be more user-friendly to be able to interactively select individual suggestions, but I think that will make the dependency resolver code much more complex than I'd like.

**Comment by J-Gras** [comment]
Another option could be to ask twice:
```
$ bro-pkg install bro-test-package
The following packages will be INSTALLED:
  bro/jsiwek/bro-test-package (1.0.5)

Proceed? [Yes/no]

...

The following packages are suggested to INSTALL
together with bro-test-package:
  bro/jsiwek/another-package (1.0.0)
  bro/jsiwek/some-package (1.0.1)

Install suggested? [Yes/no]
```
Or allow more answers:
```
$ bro-pkg install bro-test-package
The following packages will be INSTALLED:
  bro/jsiwek/bro-test-package (1.0.5)
  bro/jsiwek/another-package (1.0.0) (suggested)
  bro/jsiwek/some-package (1.0.1) (suggested)

Proceed? [Yes/skip suggested/no]
```
Actually I am not sure which approach would be best from a usability point of view. I think all three are valid choices.

**Comment by rsmmr** [comment]
Yet another option: just print out the command line to also install the suggested ones. 

Choice depends a bit on how "strongly" the suggestions would usually be I think.

**Comment by jsiwek** [comment]
The 'suggests' field is now in bro-pkg v1.3:

http://bro-package-manager.readthedocs.io/en/stable/package.html#suggests-field

**Comment by JustinAzoff** [comment]
Cool!  Will adding `suggests` to packages break older bro-pkg versions?

Also.. If this comes up again in the future, a model to maybe look into is what debian uses.  They have 2 cases for this:

Recommends

        This declares a strong, but not absolute, dependency. 
        
        The Recommends field should list packages that would be found
        together with this one in all but unusual installations. 

Suggests

        This is used to declare that one package may be more useful with
        one or more others. Using this field tells the packaging system
        and the user that the listed packages are related to this one
        and can perhaps enhance its usefulness, but that installing this
        one without them is perfectly reasonable.

**Comment by jsiwek** [comment]
> Will adding suggests to packages break older bro-pkg versions?

They should silently ignore it.

**Comment by terrencegf** [comment]
@jsiwek , it appears that bro-pkg treats the new 'suggests' field differently from the 'depends' and 'external_depends' fields when outputting JSON. Examples:

'depends' is a key,value pair:
```
bro-pkg info --jsonpretty 2 --json 'bro/corelight/bro-drwatson'
{
  "bro/corelight/bro-drwatson": {
    "metadata": {
      "master": {
        "depends": {
          "https://github.com/corelight/bro-hardware": "*"
        }, 
        "description": "Discover and log information discovered in Microsoft DrWatson messages.", 
        "script_dir": "scripts", 
        "tags": "drwatson, http, windows", 
        "test_command": "( cd tests && btest -d )"
      }
    }, 
    "url": "https://github.com/corelight/bro-drwatson", 
    "versions": []
  }
}
```

'suggests' is a simple string:
```
bro-pkg info --jsonpretty 2 --json  'bro/ncsa/bro-doctor'
{
  "bro/ncsa/bro-doctor": {
    "metadata": {
      "1.20.0": {
        "description": "A broctl plugin that helps you troubleshoot common problems\nFor cluster-related checks, the package \"add-node-names\" is recommended.", 
        "plugin_dir": ".", 
        "suggests": "\nbro/j-gras/add-node-names *", 
        "tags": "broctl plugin, troubleshoot"
      }
    }, 
    "url": "https://github.com/ncsa/bro-doctor", 
    "versions": [
      "1.0.0", 
...
    ]
  }
}
```

Was this intentional?

**Comment by jsiwek** [comment]
@terrencegf not intentional, just overlooked.  Let me know if 3ec8e7c9a26371d36dcbcd5779660b4983e24917 (now in git/master) works for you.

**Comment by terrencegf** [comment]
Thanks, I appreciate the fast fix. I ended up coding around the issue, as I suspect I'm the only one using the JSON output capability.
