### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by JonZeolla** [bro/package-manager#23]
On the [docs page](http://bro-package-manager.readthedocs.io/en/stable/bro-pkg.html) the link at the top right to edit on github is broken.  It currently points to [here](https://github.com/bro/package-manager/blob/ad14cad23c44057f11cecc5da07aeb9efb2a8af7/doc/bro-pkg.rst).  Is it supposed to go to [this](https://github.com/bro/package-manager/blob/master/doc/bro-pkg.rst)?

**Comment by jsiwek** [comment]
This looks like a bug in Read the Docs or its Sphinx theme: https://github.com/rtfd/readthedocs.org/issues/1820

I think I'd actually prefer to just remove the "Edit on GitHub" link for the stable version of the docs.  If I can't find an easy way to do that, I'll just close the ticket.

**Comment by jsiwek** [comment]
Took some trial-and-error, but the "Edit on GitHub" link should only now show on the "latest" version of the docs (in the lower left corner, switch from "stable" to "latest").  Those should always work and be directed to the master branch.

**Comment by JonZeolla** [comment]
LGTM, thanks.
