### ISSUE TITLE
local variable 'our_config_file_path' referenced before assignment during package removal

### ISSUE THREAD

**Issue by vitalyrepin** [bro/package-manager#26]
When I try to remove a package using bro-pkg remove I am getting the following error:

local variable 'our_config_file_path' referenced before assignment

Stacktrace refers to the function modified_config_files in the bropkg/manager.py

It looks like our_config_file_path variable is not initialized as none of the ifs match.

I printed out the variables used in ifs:

config_file: scripts/init.bro
their_config_file_path:  /root/.bro-pkg/clones/package/uap-bro/scripts/init.bro
script_dir:  build/scripts/VR/UAP
plugin_dir:  build

bro-pkg version: 1.3.2

**Comment by jsiwek** [comment]
In bro-pkg v1.3.3, the error/exception should be gone.  However, similar to how your ``script_dir`` points to within the ``build/`` as that's where the build process actually ends up copying the final version of the scripts, I think your package's ``config_file`` field should actually be changed to ``build/scripts/init.bro``.

**Comment by jsiwek** [comment]
Let me know if you still have problems, otherwise I've just made a PR against your package with my previous suggestion.
