### ISSUE TITLE
Don't require a __load__.bro in script dir.

### ISSUE THREAD

**Issue by J-Gras** [bro/package-manager#27]
For packages that provide a set of scripts to be loaded manually (e.g. https://github.com/J-Gras/intel-seen-more) there is a script dir but a ``__load__.bro`` is not necessary. Maybe the check during package installation can be removed.

**Comment by jsiwek** [comment]
Possibly.  Having an empty ``__load__.bro`` could be thought of as an empty ``__init__.py`` in Python which explicit mark a hierarchy of related scripts (or overloaded us of the term "package").  At least the original intent of ``__load__.bro`` was guided by Python, things are kind of a mashup of "whatever seems to work" at this point, so I'm not sure what to do here yet especially if making a change here might effect potential improvements to the way Bro's namespacing happens (e.g. nested modules).

I also just kind of like explicitly marking the script directory hierarchy of a package with a file, even if empty, so not going to make any immediate changes unless there's a bunch of more feedback on why it will be better to make them optional.

**Comment by J-Gras** [comment]
Given that this is an explicit design decision, I am totally fine with having empty ``__load__.bro`` files into script dirs for these edge-cases.
