### ISSUE TITLE
Version tag parser incompatible with tags starting with v like v0.1.0

### ISSUE THREAD

**Issue by antcodd** [bro/package-manager#32]
```bro-pkg install <package> --version v0.1.5``` fails because it does not like the version tag. Specifically the test phase succeeds but the install phase fails.

```_get_version_tags()``` appears to treat the common version tag format ```v0.1.0``` as invalid. It looks like semantic_version is being pedantic about the version tag string. 

Prepending versions with ```v``` in tags seems to be quite common, from a random survey of github repositories. This one uses it for example.

There is also inconsistency with the way ```test``` works versus ```install```. They should be using the same code for figuring out branches versus tags:

    bro-pkg install https://github.com/endace/bro-dag --version v0.1.5
    The following packages will be INSTALLED:
      https://github.com/endace/bro-dag (v0.1.5)

    Proceed? [Y/n] y
    Running unit tests for "https://github.com/endace/bro-dag"
    all 1 tests successful
    Installing "https://github.com/endace/bro-dag".
    Failed installing "https://github.com/endace/bro-dag": no such branch or version tag: "v0.1.5"

It may also be useful to look for version tag ```v0.1.5``` if specifying ```--version 0.1.5```, for things like package dependencies. N.B. we have added a 0.1.5 tag to work around this issue for now.

I'm not sure this strict semantic_version checking is necessary in general, unless the required version has a range specified.

**Comment by jsiwek** [comment]
bro-pkg v1.3.8 should now support packages that use the `vX.Y.Z` git version tag format (in addition to `X.Y.Z`).

The version specification format for dependencies hasn't changed -- they deal in strict semantic versions.  i.e. `vX.Y.Z` isn't a SemVer itself though it may be interpreted as a git tag that encodes a SemVer like "the letter 'v' followed by a SemVer".

Let me know if you find any problems, thanks.
