### ISSUE TITLE
Feature Request: Lack of a clean way to detect package nonexistance

### ISSUE THREAD

**Issue by JonZeolla** [bro/package-manager#34]
As of right now, there is not a clean way to detect if a package does not exist.  If you run `bro-pkg info` on a nonexistant package, it will tell you that it's an invalid package, but other than doing a string comparison on the current error message there doesn't seem to be a great way to check that the package isn't there.  I would suggest at least exiting non-zero.

```
user@server:~$ bro-pkg info nonexistant
"nonexistant" info:
	invalid package: package name not found in sources and not a valid git URL

user@server:~$ echo $?
0
```

**Comment by jsiwek** [comment]
Thanks, it's changed to have non-zero exit status in v1.4.0 now.
