### ISSUE TITLE
Feature Request:  Add a category argument to bro-pkg info

### ISSUE THREAD

**Issue by JonZeolla** [bro/package-manager#35]
Right now you can specify multiple packages to pull the info from using `bro-pkg info`, you can list information about categories of packages via `bro-pkg list` (installed, loaded, etc.), but it would be nice to be able to dump the details of all packages in a given category, similar to how list works.

**Comment by jsiwek** [comment]
Thanks for the suggestion.  Category arguments to `bro-pkg info` are now allowed in v.1.4.0.
