### ISSUE TITLE
Dedicated handling of broctl plugins

### ISSUE THREAD

**Issue by J-Gras** [bro/package-manager#37]
Installing broctl plugins like bro-doctor works fine but they are stored in ``bro/lib/bro/plugins/packages``, while I would expect to find a broctl plugin in ``bro/lib/broctl/plugins/packages``. However, I am not sure whether explicitly differentiating between both is worth the effort.

**Comment by jsiwek** [comment]
The filesystem location shouldn't make any significant difference to the usage scenarios, so just going to close this.
