### ISSUE TITLE
Small usability issue during installation

### ISSUE THREAD

**Issue by sethhall** [bro/package-manager#5]
The questions about proceeding don't seem to behave the way one would expect them to.  See the following interaction (i pressed enter for the apparent default selection and it asked me to type "yes" or "no" even though the printed options seem to indicate "y" or "n")

```bash
[seth@control bro-myricom (master)]$ bro-pkg --version
bro-pkg 1.0.1
[seth@control bro-myricom (master)]$ bro-pkg install .
The following packages will be INSTALLED:
  /home/seth/bro-myricom (master)

Proceed? [Y/n]
Please enter "yes" or "no" [Y/n]
```

**Comment by jsiwek** [comment]
The confirmation prompts in bro-pkg 1.0.2 should now operate similarly to apt-get's -- pressing enter defaults to yes and anything other than y/ye/yes behaves the same as n/no by aborting the operation.

**Comment by sethhall** [comment]
Thanks!
