### ISSUE TITLE
Package metadata "oscillating"

### ISSUE THREAD

**Issue by 0xxon** [bro/package-manager#6]
When updating the package metadata (potentially on different system), the ordering of the tags in individual repositories is not the same. Which leads to huge amounts of unnecessary changes in the aggragate package metadata file.

See https://github.com/bro/packages/commit/a03da82d52f59b5812e591ce045dc4fc13b13f20 for an example commit of Seth; another less extreme case is https://github.com/bro/packages/commit/f80906fb033653423790f57b8c3bcd9b5016e8f8

**Comment by jsiwek** [comment]
Should be written out in a consistent order now, providing the people/systems doing the aggregation update to the new bro-pkg 1.0.4.
